language: node_js
node_js:
  - "stable"
script:
  - npm test
  - npm ci
  - npm run ci
  - npm run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: selectors-redux.surge.sh
  project: ./build/
  on:
    branch: develop
on:
  branch: develop
