language: node_js
node_js:
  - "stable"
cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache
script:
  - npm test
  - npm run ci
  - npm run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: selectors-redux.surge.sh
  project: ./build/
  on:
    branch: develop
on:
  branch: develop
