export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const GET_PLAYER_SUCCESS = 'GET_PLAYER_SUCCESS';
export const FILTER_PLAYERS = 'FILTER_PLAYERS';
